MAX_PREFIX_LEN = 60
EXCEPTION_PREFIXES = {
    '''1. Une attestation de la maîtrise foncière sur l'emprise de ''': None,
    '''2. Un plan de l'exploitation à une échelle adaptée à la supe''': None,
    '''3. Une note succincte indiquant la nature de la substance ex''': None,
    '''4. Pour les carrières visées à la rubrique 2510-6, la justif''': None,
    '''5. Une description des modalités d'extraction et de remise e''': None,
    '''Les documents et registres prévus aux articles 3.5 et 4.7 du''': None,
    '''7. Les résultats des dernières mesures sur les effluents et ''': None,
    '''1. Le démantèlement des installations de production d'électr''': None,
    '''2. L'excavation de la totalité des fondations, jusqu'à la ba''': None,
    '''3. La remise en état qui consiste en le décaissement des air''': None,
    '''I. ― Les aires de chargement et de déchargement des produits''': 'caps',
    '''1. Les zones d'effets Z1 et Z2 définies par l'arrêté du 20 a''': None,
    '''2. La zone d'effets Z3 définie par l'arrêté du 20 avril 2007''': None,
    '''3. La zone d'effets Z4 définie par l'arrêté du 20 avril 2007''': None,
    '''4. La zone d'effets Z5 (ou la zone d'effets Z4 dans le cas o''': None,
    '''5. Les effets dominos de toute installation, équipement ou b''': None,
    '''1. Lorsque les distances d'éloignement mentionnées au point ''': None,
    '''1. Le flux horaire maximal en COV à l'exclusion du méthane, ''': None,
    '''2. Le flux horaire maximal en COV à l'exclusion du méthane, ''': None,
    '''1. Le contrôleur vérifie la présence des documents listés ai''': None,
    '''2. L'effectif au jour du contrôle, selon le registre, l'extr''': None,
    '''1. L'installation est maintenue en parfait état d'entretien,''': None,
    '''2. L'exploitant justifie de la lutte contre la prolifération''': None,
    '''1. Lorsqu'un forage alimente en eau l'installation, il est m''': None,
    '''2. L'exploitant dispose d'un moyen pour surveiller sa consom''': None,
    '''1. Les effluents d'élevage issus des bâtiments d'élevage et ''': None,
    '''2. L'exploitant justifie que les capacités des équipements d''': None,
    '''3. Tout écoulement direct des boues ou eaux polluées vers le''': None,
    '''1. Le niveau sonore des bruits en provenance de l'élevage ne''': None,
    '''2. L'émergence due aux bruits engendrés par l'installation r''': None,
    '''1. Il existe un mode d'élimination des bidons de désinfectan''': None,
    '''2. Le contrôleur s'assure que :''': None,
    '''1. Les surfaces effectivement épandues ;''': None,
    '''2. Hors zone vulnérable aux pollutions par les nitrates, les''': None,
    '''3. Les dates d'épandage ;''': None,
    '''4. La nature des cultures ;''': None,
    '''5. Les rendements des cultures ;''': None,
    '''6. Les volumes par nature d'effluents et les quantités d'azo''': None,
    '''7. Le mode d'épandage et le délai d'enfouissement ;''': None,
    '''8. Le traitement mis en œuvre pour atténuer les odeurs (s'il''': None,
    '''1. Cas des turbines :''': None,
    '''1. Cas des turbines.''': None,
    '''2. Cas des moteurs.''': None,
    '''2. Cas des moteurs :''': None,
    '''1. Lorsque la puissance est inférieure à 10 MW :''': None,
    '''2. Lorsque la puissance est supérieure ou égale à 10 MW :''': None,
    '''1. Réception :''': None,
    '''2. Expédition :''': None,
}
