MAX_PREFIX_LEN = 60
EXCEPTION_PREFIXES = {
    '''1. Le démantèlement des installations de production d'électr''': None,
    '''2. L'excavation de la totalité des fondations, jusqu'à la ba''': None,
    '''3. La remise en état qui consiste en le décaissement des air''': None,
    '''I. ― Les aires de chargement et de déchargement des produits''': 'caps',
    '''1. Les zones d'effets Z1 et Z2 définies par l'arrêté du 20 a''': None,
    '''2. La zone d'effets Z3 définie par l'arrêté du 20 avril 2007''': None,
    '''3. La zone d'effets Z4 définie par l'arrêté du 20 avril 2007''': None,
    '''4. La zone d'effets Z5 (ou la zone d'effets Z4 dans le cas o''': None,
    '''5. Les effets dominos de toute installation, équipement ou b''': None,
    '''1. Lorsque les distances d'éloignement mentionnées au point ''': None,
    '''1. Le flux horaire maximal en COV à l'exclusion du méthane, ''': None,
    '''2. Le flux horaire maximal en COV à l'exclusion du méthane, ''': None,
    '''1. Cas des turbines :''': None,
    '''1. Cas des turbines.''': None,
    '''2. Cas des moteurs.''': None,
    '''2. Cas des moteurs :''': None,
    '''1. Lorsque la puissance est inférieure à 10 MW :''': None,
    '''2. Lorsque la puissance est supérieure ou égale à 10 MW :''': None,
    '''1. Réception :''': None,
    '''2. Expédition :''': None,
}
