import os
from collections import Counter

AP_FOLDER = '/Users/remidelbouys/EnviNorma/ap_sample'


def _explore_ap_folder():
    files = os.listdir(AP_FOLDER)
    formats = Counter([file_.split('.')[-1] for file_ in files])
    odt_files = [file_ for file_ in files if file_[-3:] == 'odt']
    doc_files = [file_ for file_ in files if file_[-3:] == 'doc']
    return formats, odt_files, doc_files


APS = [
    '160906_ILM_TSI_projet APC_VuSGP.odt',
    '2014-08-05 AP_picheta_vMM.odt',
    '2014-08-12 AP_picheta_vSans Lixiviats.odt',
    '2014-09-04 AP_picheta_corr SPRN.odt',
    '201706_APC_projet.odt',
    '20181005 - Projet AP TERZEO V2 - modifs ATMOS-1.odt',
    '201909 AP poursuite exploitation_vf.odt',
    '20200701_ModŠle APMU traitement de cadavres animaux vague chaleur.odt',
    'AP L541-3.odt',
    'AP SUP SUEZ Villeparisis projet2.odt',
    'AP de suspension_vOD.odt',
    'AP mesures conservatoires_vOD.odt',
    'AP occupation sols ADEME vf.odt',
    'AP travaux ADEME.odt',
    'AP-Vaudoy_v0.odt',
    'APC 2014_focus radioactivit‚.odt',
    'APTO1 ADEMEvf.odt',
    'AP_GSM_v2 2020.odt',
    'BIOGENIE 2012-05-30 partie admin AP Vfinale.odt',
    'BIOGENIE 2014-05-05 APC d‚sorption thermique test Vfinale.odt',
    'BIONERVAL 10-08-25 notification APAUTO_vOD.odt',
    'BIONERVAL_2019-03-14_projetAPAUTO-vexploitant.odt',
    'Biogenie 2014-05-12 APC GF uniquement rubriques IED V2_PROJET.odt',
    'Jura_Photovoltaique_APC_V1.odt',
    "PJ_Projet AP d'urgence_post-accident.odt",
    'PROJET AP.odt',
    'PROJET DRIEE AP SUP pour communication propri‚taires.odt',
    'Projet AP Terz‚o V11-3.odt',
    'Projet AP urgence CGECP_vOD.odt',
    'Projet APc suivi confinement.odt',
    "Projet d'AP COSSON ST WITZ_vf.odt",
    "Projet d'AP PICHETA-SAINT MARTIN DU TERTRE.odt",
    "Projet d'APC_v0.2_vCB.odt",
    "Projet d'APC_v0.8.odt",
    'Projet_APC_SITAFD_centrale_solaire.odt',
    'Projets de modification AP origine d‚chet.odt',
    'SEMARDEL_APE.odt',
    'SEMARDEL_ISDND_Extension-Mont-Male_2013-07-08_AP_vfinale.odt',
    'SEMAVERT 2011 12 28 V projet APc_vOD.odt',
    'SEMAVERT AP Tierce Expertise 21-01-2013_vfinale.odt',
    'SEMAVERT-Extension-ISDND_AP_SUP_20-09-2013-vf.odt',
    'SEMAVERT_Mont-Male_2014-04-10_Memoire_Reponse_Recours_AP_SUP_vfinale.odt',
    "URBASYS_2020-xx-XX_APC VProjet abrogeant l'APC de 2017 v3CB.odt",
    'UTEE78_BENOIST_Projet AP_ASTREINTE_Vprojet.odt',
    'UTEE78_EMTA_3296_juin2014_Lt_…EMTA_pilote_‚vapo_lixiviatsDD_vOD.odt',
    'V1_PROJET_APC_SITA_Brueil_Casier4_mai2012.odt',
    'Vprojet_APauto_EMTA_juill2013.odt',
    "annexes 2 AP poursuite d'exploitatation et r‚injection.odt",
    'biogenie 2012-05-23 projet AP partie technique Vfinale2.odt',
    'jp212-063-projet APcomp Villeparisis.odt',
    'jp213-liboff-052-REP CLAYE GF-apcomp.odt',
    'jp213-liboff-053-SITA FD GF-apcomp.odt',
    'jp214-liboff-projet AP AUTO-vsprn.odt',
    'jp215-liboff-013-apcomp-ampliation.odt',
    'jp215-liboff-018-SITA Soignolles2 PAC-apcomp-ampliation-2.odt',
    'jp216-liboff-SITA Soignolles2-apcomp.odt',
    "projet d'APC_vCB.odt",
]

RAPPORTS_CODERST = [
    '150520_217_DBIC_rapport_coderst_sita_isdd_isdnd.odt',
    '160519_rapport au Coderst_augmentation de capacit‚.odt',
    '2014-03-18-PICHETA-RAPPORT CODERST - 355.odt',
    '2014-09-04-PICHETA-RAPPORT CODERST - 355 vMM_vOD.odt',
    '20171017_AP_SUEZ_LAFARGE_post_coderst.odt',
    'CEA 2012-08-24 rapport coderst bat 204.odt',
    'MEL 11-04-04 rapport r‚gularisation CODERST.odt',
    'Rap_auCoderst_EMTA_DAE2012_juill2013_vfinale.odt',
    'Rapport CODERST TP 18-.odt',
    'Rapport CODERST TP 18-2.odt',
    'SEMAVERT-Extension-ISDND_Rapport-CODERST_23-09-2013.odt',
    'SEMAVERT-Extension-ISDND_Rapport-CODERST_23-09-2013_vOD.odt',
    'SEMAVERT-Extension-ISDND_SUP_Rapport-CODERST_17-09-2013-vf.odt',
    'TRIADIS Rapport CODERST version 06 04 2017.odt',
    'Terz‚o - Rapport CODERST vProjet.odt',
    'URBASYS_2020-_Rapport-CODERST_vCB.odt',
    'UTEE78_EMTA_653296_13nov2014_Rap_auCoderst.odt',
    'UTEE78_EMTA_653296_13nov2014_Rap_auCoderst_vOD.odt',
    'V1_PROJET_Rap_Coderst_EMTA_m‚langeDD_tonnageDD_2012_vOD_OkDD.odt',
    'V1_PROJET_Rapp_Coderst_SITA_Brueil_Casier4_avril2012.odt',
    'V1_PROJET_Rapp_Coderst_SITA_Brueil_Casier4_avril2012_vOD_modDD.odt',
    'VProjet_Rap_auCoderst_EMTA_DAE2012_juill2013.odt',
    'VProjet_Rap_auCoderst_EMTA_DAE2012_juill2013_vOD.odt',
    'Vprojet_APauto_EMTA_Coderst_151013.odt',
    'biogenie 2012-10-03 rapport coderst Vfinale.odt',
    'biogenie 2014-05-14 rapport coderst V1_PROJET.odt',
    'biogenie 2014-05-14 rapport coderst V2_PROJET.odt',
    'biogenie 2014-05-14 rapport coderst Vfinale.odt',
    'jp214-liboff-002-rapportCODERST.odt',
    'jp214-liboff-002-rapportCODERST_vOD.odt',
]

RAPPORTS = [
    '159JB13-RAPPORT-CASIER 9_v2_vOD.odt',
    '159JB13-RAPPORT-CASIER 9_vPROJET_vOD-1.odt',
    '159JB13-RAPPORT-CASIER 9_vfinale.odt',
    '160809_283_DBIC_annexe_rapport_sitafd.odt',
    "165JB13-Rapport-Prolongation dur‚e d'exploitation_Vfinale.odt",
    '178JB13-Rapport-Projet de PT.odt',
    '192JB13-RAPPORT SUP-16 12 2013_vOD.odt',
    '2014-05_PICCONI_Rapport suite inspection vPROJET.odt',
    '2014-05_PICCONI_Rapport suite inspection vfinale.odt',
    '20140625-VAL HORIZON-PAC-rapport instruc PAC-715-vOD.odt',
    '2016-03-30_SAREN_RAPPORT_AUG-CAPACITE INCINERATION_093-V.PROJET_VuSGP.odt',
    '2018-10-08-SAO-Rapport inspection-0522.odt',
    '2018-10-08-SAO-Rapport inspection-0522_V2.odt',
    '2018-10-08-SAO-Rapport inspection-0522_vCH.odt',
    '2018-10-08-SAO-Rapport inspection-0522_vCHCB.odt',
    '201909 Rapport.odt',
    '2020-07-16 - VEOLIA-DECHARGE-PERRIER-RAPPORT - 484.odt',
    '2020-07-16 - VEOLIA-DECHARGE-PERRIER-RAPPORT - 484_CB.odt',
    '35113-RAPPORT AU PREFET-PROPOSITION DE SUPPRESSION IC.odt',
    'Annexe 2 au rapport UT95 - pmd.odt',
    'BIONERVAL_2014-03-13_Rapport-Inspection_vCG+JV.odt',
    'DS-18-R-Rapport_inspection GEREP-lettre_suites_.odt',
    'DS-18-R-Rapport_inspection GEREP-lettre_suites_v2.odt',
    'JM-13-xx-R_Rapport_‚tude impact environnemental_projet_vBJ.odt',
    'JM-13-xx-R_Rapport_‚tude impact environnemental_projet_vOD.odt',
    'MENTRE 2012-002-08 rapport inspection du 24 janvier V1_PROJET.odt',
    'MENTRE 2012-002-08 rapport inspection du 24 janvier _vOD.odt',
    'RAPPORT mentre 2014V3.odt',
    'Rapport PAC TP 18-vCB.odt',
    "Rapport d'inspection du 30-09-14 TP 14-161 .odt",
    'Rapport de non recevabilit‚ NORMAL SOUP.odt',
    'Rapport de non recevabilit‚ NORMAL SOUPE_Vprojet 19-09-2020-11h46.odt',
    'Rapport de non recevabilit‚ NORMAL SOUP_Vprojet.odt',
    'Rapport inspection GSM_V0.odt',
    'Rapport inspection GSM_V2.odt',
    'Rapport inspection GSM_VCB.odt',
    'SEMARDEL Rapport Tierce Expertise 21-01-2013 V_PROJET.odt',
    'SEMARDEL Rapport Tierce Expertise 21-01-2013_vfinale.odt',
    'SEMAVERT-Extension-ISDND_Rapport-non-recevabilite_21-01-2013_vCG.odt',
    'SEMAVERT-Extension-ISDND_Rapport-recevabilite_09-04-2013.odt',
    'SEMAVERT-Extension-ISDND_Rapport-recevabilite_09-04-2013_vfinale.odt',
    'SEMAVERT-Extension-ISDND_Rapport-recevabilite_SUP_09-04-2013.odt',
    'SEMAVERT-Extension-ISDND_Rapport-recevabilite_SUP_09-04-2013_vOD.odt',
    'SEMAVERT_ISDND_2020-08-20_Rapport_dossier_conformite_casierF2_vprojet.odt',
    'Terz‚o - Rapport  - Annexe 1.odt',
    'URBASYS 2019 02 18_ Rapport proposant lev‚e MED.odt',
    "URBASYS_2014-09-17_rapport d'inspection_VProjet2.odt",
    "URBASYS_2014-09-30_copie rapport … l'exploitant_VProjet2.odt",
    'UTEE78_BENOIST_RapportICC_V2.odt',
    'UTEE94_LES JARDINS DE L ILE DE FRANCE_6517110_2013-09-23_Rapport Inspection 2013_PROJETV1.odt',
    'V1_PROJET_Rapport octobre2014.odt',
    'historique rapports et AP.odt',
    'historique rapports et AP_v2.odt',
    'jp213-liboff-005-rapport.odt',
    'jp213-liboff-007-rapport.odt',
    'jp213-liboff-030-rapport.odt',
    'jp215-liboff-013-rapport.odt',
    'jp215-liboff-013-rapport_CB.odt',
    'jp215-liboff-018-SITA Soignolles2 PAC-rapport-1.odt',
    'jp215-liboff-018-SITA Soignolles2 PAC-rapport-1_CB.odt',
    'jp215-liboff-018-SITA Soignolles2 PAC-rapport.odt',
    'jp216-liboff-SITA Soignolles2-rapport.odt',
    'jp216-liboff-TERZEO-rapport recevabilit‚_CB.odt',
    'modŠle rapport reception casier1.odt',
    'parcellemitoyenne bledina_2019-01-30_rapport.odt',
    'rapport ADEME - vf.odt',
    'rapport ADEME - vf2.odt',
    'rapport ADEME.odt',
    'rapport de non recevabilit‚.odt',
    "transmission rapport inspection … l'exploitant TP14-162.odt",
    "transmission rapport inspection … l'exploitant TP14-162_vOD.odt",
]

AUTRES_FICHIERS_OU_AUTRES_VERSIONS_D_AP = [
    'chapitre10_brochure_texte_2017.odt',
    'chapitre3_brochure 2015-2016_texte_2015.odt',
    'chapitre3_brochure_texte2012-valideBJ&NH.odt',
    'chapitre3_brochure_texte2013.odt',
    'chapitre3_brochure_texte2013_vf.odt',
    'chapitre3_brochure_texte2013_vf_vuVV.odt',
    'chapitre3_brochure_texte_2014.odt',
    'chapitre3_brochure_texte_2014_CB.odt',
    'chapitre3_brochure_texte_2014_vuVV.odt',
    'chapitre3_brochure_texte_2015_vu_PJ.odt',
    'chapitre3_v1.odt',
    'courrier_SIAAP_traitement_boues_juillet2011.odt',
    'f‚vrier 2014 - note DGPR appel jugements transporteurs.odt',
    'f‚vrier 2014 - note DGPR appel jugements transporteurs_v2-1.odt',
    'f‚vrier 2014 - note DGPR appel jugements transporteurs_v2-vuJMC.odt',
    'f‚vrier 2014 - note DGPR appel jugements transporteurs_v2.odt',
    'f‚vrier 2014 - note DGPR appel jugements transporteurs_vOD.odt',
    'f‚vrier 2014 - note DGPR appel jugements transporteurs_vfinale.odt',
    '120130_analyse_planaction_SIAAP.odt',
    '140722_SIADIS_RAPVI_Ver_2.odt',
    '150310_Courrier DRIEE au PRIF_bilan capacit‚ SYCTOM.odt',
    '150310_Note DRIEE au PRIF_bilan capacit‚ SYCTOM.odt',
    '180404_GEN_OPESLIA_L_et_Rap_inspection.signé.odt',
    '2014-01-15-SIAAP-V2 rmPP-bj-OD.odt',
    '2014-01-15-SIAAP-V2 rmPP-bj.odt',
    '2014-01-15-SIAAP-VF3.odt',
    '20140527-note accompagnement courrier SIAAP.odt',
    '2018 11 20 - R‚ponse PRIF … Paprec.odt',
    '2018 11 20 - R‚ponse PRIF … Paprec_jg.odt',
    '2018 12 13 - R‚ponse PRIF … Paprec v2.odt',
    '2019-06-05_COGETRAD_RAPVI_0408_v3.odt',
    '201909 AP poursuite exploitation.odt',
    '201909 AP poursuite exploitation_test.odt',
    '201909 AP poursuite exploitation_v2.odt',
    '201909 AP poursuite exploitation_vCB.odt',
    'AP SUP SUEZ Villeparisis projet.odt',
    'AP de suspension .odt',
    'AP mesures conservatoires .odt',
    'AP mise en demeure r‚gularisation .odt',
    'AP occupation sols ADEME-1 mod GB.odt',
    'AP occupation sols ADEME.odt',
    'APTO1 ADEME-mod GB.odt',
    'BIOGENIE 2014-05-05 APC d‚sorption thermique test V1_PROJET.odt',
    'BIOGENIE 2014-05-05 APC d‚sorption thermique test V2_PROJET.odt',
    'BIOGENIE 2014-05-05 APC d‚sorption thermique test V2_vSPRN.odt',
    'Biogenie 2014-05-12 APC GF uniquement rubriques IED V1_PROJET.odt',
    'Brochure_m‚thode pour graphes d‚chets.odt',
    'Cadrage r‚duction de capacit‚s.odt',
    'Courrier DRIEE DGPR APTO APOS.odt',
    'Courrier DRIEE DGPR APTO2.odt',
    'Let_nap_beauce_v0.odt',
    'Let_nap_beauce_vfinale.odt',
    'Lettre_CAPM 010813_VFINALE.odt',
    'M‚thanisation77. Projet.Applicatif.odt',
    'Not_SEMAVERT_dokchapo_avril12.odt',
    'Not_SEMAVERT_dokchapo_avril12_v0.odt',
    'Not_SEMAVERT_dokchapo_avril12_vOD.odt',
    'Projet AP TERZEO V2 - modifs ATMOS.odt',
    'Projet AP Terz‚o V10.odt',
    'Projet AP Terz‚o V11-1.odt',
    'Projet AP Terz‚o V11-2.odt',
    'Projet AP Terz‚o V11.odt',
    'Projet AP Terz‚o V9.odt',
    'Projet AP Terz‚o base catalogue.odt',
    'Projet AP Terz‚o base catalogue_V2.odt',
    'Projet AP Terz‚o base catalogue_V3.odt',
    'Projet AP Terz‚o base catalogue_V4.odt',
    'Projet AP Terz‚o base catalogue_V5.odt',
    'Projet AP Terz‚o base catalogue_V6.odt',
    'Projet AP Terz‚o base catalogue_V7.odt',
    'Projet AP Terz‚o base catalogue_V8.odt',
    'Projet AP Terz‚o.odt',
    'Projet AP Terz‚o_V1 transmise.odt',
    'Projet AP Terz‚o_V3.odt',
    'Projet AP urgence CGECP_vfinale.odt',
    "Projet d'AP COSSON ST WITZ.odt",
    "Projet d'AP COSSON ST WITZ_v2.odt",
    "Projet d'AP COSSON ST WITZ_v3.odt",
    "Projet d'AP COSSON ST WITZ_v3_UT95.odt",
    "Projet d'AP COSSON ST WITZ_v5.odt",
    "Projet d'AP COSSON ST WITZ_v5_vOD.odt",
    "Projet d'APC_v0.2.odt",
    'Rapp_Recevabilit‚_DDAE_EMTA_2014.odt',
    'SEMARDEL_ISDND_Extension-Mont-Male_2013-07-08_AP.odt',
    'SEMARDEL_ISDND_Extension-Mont-Male_2013-07-08_AP_v2.odt',
    'SEMARDEL_ISDND_Extension-Mont-Male_2013-07-08_AP_vOD.odt',
    'SEMAVERT 2011 12 28 V projet APc.odt',
    'SEMAVERT AP Tierce Expertise 21-01-2013 V_PROJET.odt',
    'SEMAVERT-Extension-ISDND_AP_SUP_09-04-2013.odt',
    'SEMAVERT-Extension-ISDND_AP_SUP_09-04-2013_vOD.odt',
    'SEMAVERT_Mont-Male_2014-04-10_Memoire_Reponse_Recours_AP_SUP_v2.odt',
    'SEMAVERT_Mont-Male_2014-04-10_Memoire_Reponse_Recours_AP_SUP_v2_vOD.odt',
    "URBASYS_2020-xx-XX_APC VProjet abrogeant l'APC de 2017 suite comentaires exploitant et ‚change avec FB.odt",
    "URBASYS_2020-xx-XX_APC VProjet abrogeant l'APC de 2017 suite comentaires exploitant et ‚change avec FB_CB.odt",
    'UTEE78_SITA_Arnouville_653095_juin2014_Rap_DemandeCompl‚ments_SUP.odt',
    'V1 projet Lettre_CAPM 010813.odt',
    'V1_PROJET_APC_SITA_Brueil_Casier4_avril2012.odt',
    'V1_PROJET_Rap_Insp_EMTA_1erOct12.odt',
    'V1_PROJET_Rap_Insp_SITA_casier4_26f‚v2013.odt',
    'V1_PROJET_Rapp_Casier_U1_EMTA_Guitrancourt_dec11.odt',
    'V1_PROJET_Rapp_Casier_U1_EMTA_Guitrancourt_dec11_vOD.odt',
    'V_PROJET_Rap_DemandeCompl‚ments_SUP_SITA_Arnouville.odt',
    'analyse_r‚ponse_SIAAP30aout2011_VSPRN_30sept2011.odt',
    'biogenie 2012-05-23 projet AP partie technique V2_PROJET_vOD.odt',
    'biogenie 2012-05-23 projet AP partie technique Vfinale.odt',
    'capoulade proposition.odt',
    'jp215-liboff-018-SITA Soignolles2 PAC-apcomp-ampliation.odt',
    'premiŠreanalyse_r‚ponse_SIAAP30aout2011_V27sept2011.odt',
    'proc‚dure PIG appliqu‚e … IPXIII SYCTOM.odt',
    "projet d'APC.odt",
    'syntheserapdebus761.odt',
]
