# Apply to all files without commiting:
#   pre-commit run --all-files
# Update this file:
#   pre-commit autoupdate
repos:
  - repo: local
    hooks:
      - id: pytest
        name: pytest
        stages: [commit]
        language: system
        entry: bash -c "cd src ; pytest"
        types: [python]
        verbose: true
        pass_filenames: false
        always_run: true
      - id: pytest-mypy envinorma
        name: pytest-mypy envinorma
        stages: [commit]
        language: system
        entry: bash -c "cd src ; pytest --mypy-ignore-missing-imports envinorma"
        types: [python]
        verbose: true
        pass_filenames: false
        always_run: true
